server:
  port: 8765

spring:
  application:
    name: "api-gate-way"

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false
      routes:
        - id: micro-service-1
          uri: lb://micro-service-1    # lb:// - будет искать сервис через Эврику
          predicates:
            - Path=/serviceA/**
        - id: micro-service-2
          uri: lb://micro-service-2
          predicates:
            - Path=/serviceB/**
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka
